import { BEACON_CORE_PATH, BEACON_PATHS, WARDEN_PATHS } from "@warden/ui/lib/brand";
import { cn } from "@warden/ui/lib/utils";

/** SVG shell shared by the marks: lucide's grid and light stroke, `currentColor`. */
function Mark({ className, children }: { className?: string; children: React.ReactNode }) {
  return (
    <svg
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth={1.5}
      strokeLinecap="round"
      strokeLinejoin="round"
      className={cn("size-5 shrink-0", className)}
      aria-hidden
    >
      {children}
    </svg>
  );
}

export function WardenMark({ className }: { className?: string }) {
  return (
    <Mark className={className}>
      {WARDEN_PATHS.map((d) => (
        <path key={d} d={d} />
      ))}
    </Mark>
  );
}

/** The core takes `--brand-core`; at favicon sizes use the static icon.svg generated by brand/build.ts. */
export function BeaconMark({ className }: { className?: string }) {
  return (
    <Mark className={className}>
      <path d={BEACON_CORE_PATH} className="stroke-brand-core" />
      {BEACON_PATHS.map((d) => (
        <path key={d} d={d} />
      ))}
    </Mark>
  );
}
